### ISSUE TITLE
2 Lutron Caseta bridges causes errors that slow down Homebridge

### ISSUE THREAD

**Issue by TerryLeeWhite** [thenewwazoo/homebridge-lutron-caseta-leap#96] opened 2023-01-05 01:56 UTC
**Describe The Bug:**
 I have two bridges and Associate one with the plugin. Then the Leap plugin constantly gives an error that it has no credentials for the other bridge that's NOT associated. 

**To Reproduce:**
 just having two Lutron bridges and associating one. 

**Expected behavior:**
 not having the 2nd bridge cause errors. 

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

[1/4/2023, 8:05:45 PM] [Lutron] Could not connect to discovered hub: Error: no credentials for bridge ID 01F07DD7
at LutronCasetaLeap.handleBridgeDi scovery (/usr/local/lib/node_ modules/h omebridge-lutron-caseta-leap/src/platf orm.ts:180:19)
at BridgeFinder.emit (node:events:
527:28)
at /usr/local/lib/node modules /hom ebridge-lutron-caseta-leap/node_ module s/lutron-leap/src/BridgeFinder.ts:45:2
6
[1/4/2023, 8:05:48 PM] [Ring]

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment] 2023-01-05 06:18
Lutron bridges announce themselves every so often, and the plugin will search for them every so often. When they're found, an attempt is made to connect, and if there are no credentials, an error is printed. This occasional-discovery-and-connection process is by design, and is the only way bridges are _ever_ found. This failure is, in cases such as yours, expected to be benign, and you should be able to ignore it. Is it causing any other problematic behaviors? I'm also open to suggestions about how I can improve the error. Not many people running the plugin have intentionally-unconfigured bridges. :)

**Comment by TerryLeeWhite** [comment] 2023-01-05 14:02
Yes the problem is that it slows down my entire HomeBridge. I had to disable the plugin to get all my other accessories to stop saying "updating" or no response. Once I disabled your plugin performance returned to normal. My suggestion would be let us associate all bridges and then pick the primary one.

**Comment by thenewwazoo** [comment] 2023-01-05 15:33
Oh that’s quite curious about the slowdown. I’ll have to see if I can reproduce. I’m not sure why that would have happened.  Any chance you can give me a complete debug log that shows the error during slowdown?

And thank you for the support!

**Comment by TerryLeeWhite** [comment] 2023-01-05 17:57
Now it just got weirder. When I enabled the plugin and DEBUG. It worked well and there was no performance hit. However, as soon as I turned DEBUG off again and rebooted the performance tanked. 
[LutronLeapDebug-TerryWhite.txt](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/10354519/LutronLeapDebug-TerryWhite.txt)

**Comment by MoTechnicalities** [comment] 2023-01-05 17:58
@TerryLeeWhite 
I'd highly recommend setting up the plugin in a Child Bridge.

**Comment by TerryLeeWhite** [comment] 2023-01-05 18:30
@MoTechnicalities you're a life saver! That did the trick. Thanks for pushing me to investigate Child Bridges, and set one up. That was my first although I've heard people talk about them since the feature came out. I get it now. It solved the performance problem.

**Comment by MoTechnicalities** [comment] 2023-01-05 19:03
@TerryLeeWhite
Great! Now that you've moved to the Child Bridg, check and remove unneeded cashed duplicates in the **Homebridge Settings**. You can check the listed devices against the currently working ones found in the Home App. **ONLY REMOVE THE UNNEEDED ONES!**

I found duplicate cashed accessories (bridge & remotes) linked to the old bridge ID. Have Fun!

![image](https://user-images.githubusercontent.com/68468472/210856323-63cfa8e3-634a-4c57-b0cd-da41be6e8bbf.png)

![image](https://user-images.githubusercontent.com/68468472/210857367-f592d759-a63c-4e21-a1f0-dc3d56ef958f.png)

![image](https://user-images.githubusercontent.com/68468472/210859200-a3a2be15-4018-4e30-bbcb-bdf1595cf9e3.png)

![image](https://user-images.githubusercontent.com/68468472/210858854-12657203-45a1-45dc-9dff-e46efed102b5.png)

**Comment by TerryLeeWhite** [comment] 2023-01-05 19:54
thanks! got it.

**Comment by thenewwazoo** [comment] 2023-01-06 03:37
Holy shit, @MoTechnicalities, that's amazing. Thank you so much for helping @TerryLeeWhite out.

**Comment by thenewwazoo** [comment] 2023-01-06 03:39
@TerryLeeWhite, I'm going to close this but link it to #92, and will update the README when I have a chance (unless @MoTechnicalities beats me to it, and I might steal those images 😆 )

**Closed by thenewwazoo** 2023-01-06 03:39 UTC
Labels: bug
