### ISSUE TITLE
Occupancy Sensor not reporting Status

### ISSUE THREAD

**Issue by markhurlburt** [thenewwazoo/homebridge-lutron-caseta-leap#47] opened 2022-05-15 15:14 UTC
**Describe The Bug:**

I'm running 2.3.6 with the PD-OSENS-WH sensor and while it shows up in Homekit it always reports no occupancy and doesn't seem to be working... 

<img width="861" alt="image" src="https://user-images.githubusercontent.com/303958/168479925-a0dd3b23-1cfb-43f8-ab83-72601ab4cd82.png">

![IMG_0324](https://user-images.githubusercontent.com/303958/168479951-3ff3f858-b7ab-4e73-ab3e-9a24d3449ab1.PNG)

**To Reproduce:**

This may be user error?

**Expected behavior:**

I expected the motion detector in Homekit to register motion/occupancy/whatever

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
[15/05/2022, 10:07:16] [HB Supervisor] Restarting Homebridge...
[15/05/2022, 10:07:16] [HB Supervisor] Starting Homebridge with extra flags: -I
[15/05/2022, 10:07:16] [HB Supervisor] Started Homebridge v1.4.1 with PID: 1508
[15/05/2022, 10:07:18] Loaded config.json with 0 accessories and 2 platforms.
[15/05/2022, 10:07:19] Loaded 1 cached accessories from cachedAccessories.
[15/05/2022, 10:07:19] ---
[15/05/2022, 10:07:25] Loaded plugin: homebridge-broadlink-rm-pro@4.4.10
[15/05/2022, 10:07:25] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
[15/05/2022, 10:07:25] ---
[15/05/2022, 10:07:25] Loaded plugin: homebridge-config-ui-x@4.44.1
[15/05/2022, 10:07:25] Registering platform 'homebridge-config-ui-x.config'
[15/05/2022, 10:07:25] ---
[15/05/2022, 10:07:26] Loaded plugin: homebridge-lutron-caseta-leap@2.3.6
[15/05/2022, 10:07:26] Registering platform 'homebridge-lutron-caseta-leap.LutronCasetaLeap'
[15/05/2022, 10:07:26] ---
[15/05/2022, 10:07:26] Loading 2 platforms...
[15/05/2022, 10:07:26] [Config] Initializing config platform...
[15/05/2022, 10:07:26] [Config] Running in Service Mode
[15/05/2022, 10:07:26] [Lutron] Initializing LutronCasetaLeap platform...
[15/05/2022, 10:07:26] [Lutron] LutronCasetaLeap starting up...
[15/05/2022, 10:07:26] [Lutron] LutronCasetaLeap plugin finished early initialization
[15/05/2022, 10:07:26] [Lutron] Restoring cached Pico3ButtonRaiseLower 153f2297-24f2-482c-9fda-ff3538aaa98d on bridge 047d7775
[15/05/2022, 10:07:26] [Lutron] Restoring Pico remote Living Room Pico on bridge 047d7775
[15/05/2022, 10:07:26] [Lutron] Finished launching; starting up automatic discovery
[15/05/2022, 10:07:26] Homebridge v1.4.1 (HAP v0.10.2) (Homebridge 0DEA) is running on port 51757.
[15/05/2022, 10:07:27] [Lutron] Device type SmartBridge supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Accessory Pico3ButtonRaiseLower 153f2297-24f2-482c-9fda-ff3538aaa98d Living Room Remote already set up. Skipping.
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Device type WallDimmer supported natively, skipping setup
[15/05/2022, 10:07:27] [Lutron] Found a new RPSOccupancySensor occupancy sensor Kitchen Motion Sensor
[15/05/2022, 10:07:27] [Lutron] Finished setting up Pico remote Living Room Pico
[15/05/2022, 10:12:27] [Homebridge UI] [admin] Accessory layout changes saved.

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment] 2022-05-15 16:09
Thanks for the report. Can you [enable debug logging](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap#-enabling-debugging) and provide the contents of the log after a restart and after you've confirmed it doesn't work?

One thing that might help is setting the sensor's timeout to 1 minute and pointing it at a wall. That reduces the amount of time you need to wait for it to reset so you can test.

**Comment by thenewwazoo** [comment] 2022-06-22 05:10
I'm going to close this up due to age. Please let me know if the problem persists and you're able to collect debug logs.

**Closed by thenewwazoo** 2022-06-22 05:10 UTC
Labels: bug
