### ISSUE TITLE
Restarting HomeBridge can cause some Picos to lose assignments

### ISSUE THREAD

**Issue by Zakharov123** [thenewwazoo/homebridge-lutron-caseta-leap#70] opened 2022-08-21 13:29 UTC
I have noticed that restarting homebridge can cause certain Pico remotes to forget what devices they control.  This only happens when the pico controls devices that do not have native HomeKit support-- in my case I use a TP-Link HomeBridge plugin to access certain smartplugs.  My theory is that due to some race condition, the Caseta LEAP plugin initializes before the TP-Link plugin can finish creating its devices, so the Pico cannot see the TP-Link smartplug, therefore the Pico loses its assignments. 

Is there a way to sort the initialization order of the plugin? Or to put a delay to make sure it initializes last?

**Comment by thenewwazoo** [comment] 2022-08-22 02:54
I spent a bit of time trying to reproduce this by adding a dummy switch device and configuring the button to toggle it, and then inserting a delay into the dummy switch startup, but wasn't able to reproduce it.

Is it perfectly repeatable, or is there some randomness to it? If the TP-Link were (for some crazy reason) un-registering and re-registering devices, they would disappear from Pico configurations, but also from scenes too. Have you noticed that happening as well? If you can grab a log starting just before a restart, that'll help me narrow down whether accessories are being restored from cache.

**Comment by Zakharov123** [comment] 2022-08-22 16:40
It is intermittent.  Below is a log of a restart after which it forgot the device.  The TPlink device is:

[Mist] plug [80062A82C77E019F65EF45673F761AFD1EE004A5] 192.168.1.146 9999

The Pico device is:
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico2Button remote Mist Pico

Thanks for developing and supporting this plugin, it's great.

LOG:
---------------------------------

[37m[8/22/2022, 11:17:51 AM] [39m[36m[Lutron][39m Button /button/143 on Pico remote Office Pico got action Press
[37m[8/22/2022, 11:17:51 AM] [39m[36m[Lutron][39m Button /button/143 on Pico remote Office Pico got action Release
[37m[8/22/2022, 11:17:51 AM] [39m[36m[Lutron][39m button /button/143 got a short press
[0;37m[8/22/2022, 11:28:36 AM] [0m[0;36m[Homebridge UI][0m Homebridge restart request received
[0;37m[8/22/2022, 11:28:36 AM] [0m[0;36m[Homebridge UI][0m UI / Bridge settings have not changed; only restarting Homebridge process
[0;37m[8/22/2022, 11:28:36 AM] [0m[0;36m[Homebridge UI][0m Sending SIGTERM to Homebridge
[37m[8/22/2022, 11:28:36 AM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: null, Signal: SIGTERM
[37m[8/22/2022, 11:28:41 AM][0m [36m[HB Supervisor][0m Restarting Homebridge...
[37m[8/22/2022, 11:28:41 AM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -I
[37m[8/22/2022, 11:28:41 AM][0m [36m[HB Supervisor][0m Started Homebridge v1.5.0 with PID: 26488
[37m[8/22/2022, 11:28:41 AM] [39mLoaded config.json with 0 accessories and 5 platforms.
[37m[8/22/2022, 11:28:41 AM] [39mLoaded 11 cached accessories from cachedAccessories.
[37m[8/22/2022, 11:28:41 AM] [39m---
[37m[8/22/2022, 11:28:41 AM] [39mLoaded plugin: homebridge-config-ui-x@4.50.0
[37m[8/22/2022, 11:28:41 AM] [39mRegistering platform 'homebridge-config-ui-x.config'
[37m[8/22/2022, 11:28:41 AM] [39m---
[37m[8/22/2022, 11:28:41 AM] [39mLoaded plugin: homebridge-lutron-caseta-leap@2.4.2
[37m[8/22/2022, 11:28:41 AM] [39mRegistering platform 'homebridge-lutron-caseta-leap.LutronCasetaLeap'
[37m[8/22/2022, 11:28:41 AM] [39m---
[37m[8/22/2022, 11:28:42 AM] [39m[33mDisabled plugin: homebridge-ring@11.0.7[39m
[37m[8/22/2022, 11:28:42 AM] [39m---
[37m[8/22/2022, 11:28:42 AM] [39mLoaded plugin: homebridge-tplink-smarthome@7.0.1
[37m[8/22/2022, 11:28:42 AM] [39mRegistering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[37m[8/22/2022, 11:28:42 AM] [39m---
[37m[8/22/2022, 11:28:42 AM] [39m[33mThe plugin "homebridge-wemo" requires Node.js version of ^14.19.3 || ^16.15.1 which does not satisfy the current Node.js version of v16.15.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF[39m
[37m[8/22/2022, 11:28:42 AM] [39mLoaded plugin: homebridge-wemo@5.0.3
[37m[8/22/2022, 11:28:42 AM] [39mRegistering platform 'homebridge-wemo.Wemo'
[37m[8/22/2022, 11:28:42 AM] [39m---
[37m[8/22/2022, 11:28:42 AM] [39mLoading 5 platforms...
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Initializing TplinkSmarthome platform...
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Initializing child bridge 0E:D3:64:47:55:85
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m Initializing Wemo platform...
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m Initialising plugin v5.0.3 | System win32 | Node v16.15.0 | HB v1.5.0 | HAPNodeJS v0.10.2...
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m [33mConfig entry [manualDevices] is unused and can be removed.[39m
[37m[8/22/2022, 11:28:42 AM] [39m[33mIgnoring config for the platform "Ring" in your config.json as the plugin "homebridge-ring" has been disabled.[39m
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Lutron][39m Initializing LutronCasetaLeap platform...
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Lutron][39m LutronCasetaLeap starting up...
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Lutron][39m LutronCasetaLeap plugin finished early initialization
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m Plugin initialised. Setting up accessories....
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Lutron][39m Finished launching; starting up automatic discovery
Setup Payload:
X-HM://0024340C2QPH7
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[30m[47m                       [49m[39m
[30m[47m    ┌────────────┐     [49m[39m
[30m[47m    │ 372-52-530 │     [49m[39m
[30m[47m    └────────────┘     [49m[39m
[30m[47m                       [49m[39m
[37m[8/22/2022, 11:28:42 AM] [39mHomebridge v1.5.0 (HAP v0.10.2) (Homebridge CB13) is running on port 51526.
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m [Headboard] initialising with options {"logging":"standard","showAs":"switch"}.
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m [Headboard] initialised with s/n 221614K13009D1 and ip/port 192.168.1.62:49153
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m [Headboard] http has been established.
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m [Headboard] upnp has been established.
[37m[8/22/2022, 11:28:42 AM] [39m[36m[Wemo][39m [Headboard] current state [off].
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Launched child bridge with PID 32404
[37m[8/22/2022, 11:28:42 AM] [39mRegistering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Loaded homebridge-tplink-smarthome v7.0.1 child bridge successfully
[37m[8/22/2022, 11:28:42 AM] [39mLoaded 12 cached accessories from cachedAccessories.0ED364475585.
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m homebridge-tplink-smarthome v7.0.1, node v16.15.0, homebridge v1.5.0, api v2.7
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Christmas Tree] UUID: bab9deb3-6f80-4fcf-8e73-8829ceabc62b deviceId: 8006CAD70F6CF92E5457B71DBF7131A31E1FD3EF 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Motion Hub Front] UUID: e1077dc6-5405-4c17-9fa3-933f5665640a deviceId: 800605F7885A9E8196A042DD3A8C96D71E1F9BE1 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Patio Eve Lights] UUID: c87de5ca-29e1-498b-afe8-21a196753737 deviceId: 80063F2EB82D28B2CE8038803E41DEC01D056CE4 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Garage Lanterns] UUID: 813a59e6-8e8c-48a8-abbf-839fcb724a3d deviceId: 8006034D1DCBDAB7DA8FC63CE5DA4C371D033E82 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Motion Hub Back] UUID: de1bf908-3282-46db-89d0-1846d4c6d9e9 deviceId: 8006E06C8D66AA8418ACA1D15BD3D9BC1E177903 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Garage Eve Lights] UUID: 16ecf92f-a953-44e7-a4c1-9ab355a8463d deviceId: 8006A9FB4464E11648F2481BDC6377A01D0299DA 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Garage] UUID: 5a96c818-d5e8-4edd-ba6b-12f7825643ca deviceId: 8006D565323FA19BC18F7E5C187343A41B4784A5 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Greenhouse One] UUID: 0ac1c1b0-b011-40ab-aa63-7ad4e5593ac8 deviceId: 8006BE1A2074B721F2797DDC6CDCCB951ED71C0B 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Office Lamp] UUID: 5a409191-fafc-4620-9543-f6ea70b9adb8 deviceId: 8006EABA52CC71855A28B3A2AE0CD5DE1E1FAA7E 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Doorbell Transformer] UUID: 8e631cc2-690a-40c9-9661-e7c21963544d deviceId: 80063DEB4787EFA3A697CF124FA5F5BC1EE17BCC 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [Greenhouse Two] UUID: 1e1bc679-538f-41b9-955b-140a974604f2 deviceId: 80060E4E9348F95DABCB9D9AB1E525521ED73601 
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Configuring cached accessory: [TP-LINK_Smart Plug_6BE9] UUID: 53887782-ab78-493d-acf1-410faa7a8ca7 deviceId: undefined 
[37m[8/22/2022, 11:28:42 AM] [39mHomebridge v1.5.0 (HAP v0.10.2) (TplinkSmarthome) is running on port 49176.
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Garage Lanterns] plug [8006034D1DCBDAB7DA8FC63CE5DA4C371D033E82] 192.168.1.220 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Garage Lanterns] plug [8006034D1DCBDAB7DA8FC63CE5DA4C371D033E82]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Motion Hub Front] plug [800605F7885A9E8196A042DD3A8C96D71E1F9BE1] 192.168.1.163 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Motion Hub Front] plug [800605F7885A9E8196A042DD3A8C96D71E1F9BE1]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Christmas Tree] plug [8006CAD70F6CF92E5457B71DBF7131A31E1FD3EF] 192.168.1.112 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Christmas Tree] plug [8006CAD70F6CF92E5457B71DBF7131A31E1FD3EF]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Doorbell Transformer] plug [80063DEB4787EFA3A697CF124FA5F5BC1EE17BCC] 192.168.1.135 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Doorbell Transformer] plug [80063DEB4787EFA3A697CF124FA5F5BC1EE17BCC]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Motion Hub Back] plug [8006E06C8D66AA8418ACA1D15BD3D9BC1E177903] 192.168.1.164 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Motion Hub Back] plug [8006E06C8D66AA8418ACA1D15BD3D9BC1E177903]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Mist] plug [80062A82C77E019F65EF45673F761AFD1EE004A5] 192.168.1.146 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Mist] plug [80062A82C77E019F65EF45673F761AFD1EE004A5]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Greenhouse One] plug [8006BE1A2074B721F2797DDC6CDCCB951ED71C0B] 192.168.1.114 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Greenhouse One] plug [8006BE1A2074B721F2797DDC6CDCCB951ED71C0B]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Garage] plug [8006D565323FA19BC18F7E5C187343A41B4784A5] 192.168.1.63 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Garage] plug [8006D565323FA19BC18F7E5C187343A41B4784A5]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Greenhouse Two] plug [80060E4E9348F95DABCB9D9AB1E525521ED73601] 192.168.1.113 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Greenhouse Two] plug [80060E4E9348F95DABCB9D9AB1E525521ED73601]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Garage Eve Lights] plug [8006A9FB4464E11648F2481BDC6377A01D0299DA] 192.168.1.234 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Garage Eve Lights] plug [8006A9FB4464E11648F2481BDC6377A01D0299DA]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Patio Eve Lights] plug [80063F2EB82D28B2CE8038803E41DEC01D056CE4] 192.168.1.235 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Patio Eve Lights] plug [80063F2EB82D28B2CE8038803E41DEC01D056CE4]
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Device First Online: [Office Lamp] plug [8006EABA52CC71855A28B3A2AE0CD5DE1E1FAA7E] 192.168.1.162 9999
[37m[8/22/2022, 11:28:42 AM] [39m[36m[TplinkSmarthome][39m Adding: [Office Lamp] plug [8006EABA52CC71855A28B3A2AE0CD5DE1E1FAA7E]
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico2Button remote Main Lights Remote 1
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico2Button remote Main Lights Remote 2
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico2Button remote Main Lights 2 Remote 1
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico2Button remote Main Lights 2 Remote 2
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico3ButtonRaiseLower remote Attic Pico 1
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico3ButtonRaiseLower remote Attic Pico 2
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico3ButtonRaiseLower remote Unnamed Pico Remote 1
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico2Button remote Nursery Pico
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico2Button remote Office Pico
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m Found a new Pico2Button remote Mist Pico
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Smart Bridge: Skipping: Device type SmartBridge supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Family Family Room 1: Skipping: Device type WallDimmer supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Family Family Room 2: Skipping: Device type WallDimmer supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Family Family Room Fireplace: Skipping: Device type WallDimmer supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Master Bedroom Master Nightlight: Skipping: Device type WallDimmer supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Kitchen Two: Skipping: Device type WallSwitch supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire cached device Main Lights Remote 1: Skipping: Associated with a device outside HomeKit[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire cached device Main Lights Remote 2: Skipping: Associated with a device outside HomeKit[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Kitchen Lights: Skipping: Device type WallSwitch supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire cached device Main Lights 2 Remote 1: Skipping: Associated with a device outside HomeKit[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire cached device Main Lights 2 Remote 2: Skipping: Associated with a device outside HomeKit[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Master Bathroom Fireplace: Skipping: Device type WallSwitch supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Office Shade: Skipping: Device type SerenaHoneycombShade not recognized. Please file a ticket and tell me about it[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Attic Lights: Skipping: Device type WallDimmer supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire cached device Attic Pico 1: Skipping: Associated with a device outside HomeKit[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire cached device Attic Pico 2: Skipping: Associated with a device outside HomeKit[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Foyer Chandelier: Skipping: Device type WallDimmer supported natively, skipping setup[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Nursery Shade: Skipping: Device type SerenaHoneycombShade not recognized. Please file a ticket and tell me about it[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Garden New Fountain: Skipping: Device type OutdoorPlugInSwitch not recognized. Please file a ticket and tell me about it[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Outdoor Lights Porch Garage Side: Skipping: Device type OutdoorPlugInSwitch not recognized. Please file a ticket and tell me about it[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Porch Outdoor Porch Kelly Side: Skipping: Device type OutdoorPlugInSwitch not recognized. Please file a ticket and tell me about it[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire cached device Unnamed Pico Remote 1: Skipping: Associated with a device outside HomeKit[39m
[37m[8/22/2022, 11:28:43 AM] [39m[36m[Lutron][39m [31mFailed to process device: Error: Failed to wire new device Lounge Repeater: Skipping: Device type WirelessAuxRepeater not recognized. Please file a ticket and tell me about it[39m
[37m[8/22/2022, 11:28:44 AM] [39m[36m[Wemo][39m ✓ Setup complete. Want to see this plugin in your own language? Let me know!

**Comment by thenewwazoo** [comment] 2022-08-22 17:07
I suspect the problem lies with the TP-Link plugin. Check out these lines:

```
�[37m[8/22/2022, 11:28:42 AM] �[39m�[36m[TplinkSmarthome]�[39m Device First Online: [Mist] plug [80062A82C77E019F65EF45673F761AFD1EE004A5] 192.168.1.146 9999
�[37m[8/22/2022, 11:28:42 AM] �[39m�[36m[TplinkSmarthome]�[39m Adding: [Mist] plug [80062A82C77E019F65EF45673F761AFD1EE004A5]
```

That looks like this plug is being configured for the first time, which makes it look "new" to HomeKit. I'd be a shiny nickel that you don't see this line after a restart that doesn't have the problem.

**Comment by thenewwazoo** [comment] 2022-09-13 16:58
I'm going to close this up. Please re-open it if you're able to connect w/ the TP-Link plugin devs and discover my theory is incorrect. Thank you for the report, it definitely gave me a new avenue for investigationof future issues!

**Closed by thenewwazoo** 2022-09-13 16:58 UTC
