### ISSUE TITLE
Hoobs configuration setup

### ISSUE THREAD

**Issue by tekstein** [thenewwazoo/homebridge-lutron-caseta-leap#38] opened 2022-04-04 04:07 UTC
**Describe Your Problem:**

need help on install on hoobs systems. I don't have the associate button that I've seen in install guides. Do I need to install via legacy? 
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
[log-2.txt](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/files/8406621/log-2.txt)

Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.19.1
* **NPM Version**: unsure
* **Operating System**: hoobs 4.0.104
<img width="885" alt="Screen Shot 2022-04-03 at 10 24 54 PM" src="https://user-images.githubusercontent.com/35672015/161471517-9b20c329-3dc1-47d0-a74d-3fa274dd73ee.png">
<img width="885" alt="Screen Shot 2022-04-03 at 10 25 18 PM" src="https://user-images.githubusercontent.com/35672015/161471518-7b70ca50-ab84-4e6a-bc35-ed63a11e08c3.png">
<img width="856" alt="Screen Shot 2022-04-03 at 10 27 03 PM" src="https://user-images.githubusercontent.com/35672015/161471519-2756a44e-f13a-4692-84b0-04f6fa759f4a.png">
<img width="1130" alt="Screen Shot 2022-04-03 at 10 27 20 PM" src="https://user-images.githubusercontent.com/35672015/161471520-b8f384a2-1b33-4000-a894-9b34509e220f.png">

**Comment by ftoralesacosta** [comment] 2022-04-04 05:51
Hey, thanks for the awesome plugin!

Just want to report I'm also having trouble with this plugin and HOOBS UI. I used the legacy instructions, but I'm getting errors as well. I'm pretty sure these errors are because copying and pasting the certificates and keys introduced an error (additional new lines or "/" ).

`4/3/2022, 8:13:55 PMLutron Caseta Leap Bridge starting
4/3/2022, 8:14:00 PMLutron Caseta Leap BridgeLoaded plugin 'homebridge-lutron-caseta-leap'
4/3/2022, 8:14:00 PMLutron Caseta Leap BridgeLoading 1 platforms...
4/3/2022, 8:14:00 PMLutron Caseta Leap BridgeLutronCasetaLeapLutronCasetaLeap starting up...
4/3/2022, 8:14:00 PMLutron Caseta Leap BridgeLutronCasetaLeapLutronCasetaLeap plugin finished early initialization
4/3/2022, 8:14:00 PMLutron Caseta Leap BridgeLutronCasetaLeapFinished launching; starting up automatic discovery
4/3/2022, 8:14:00 PMLutron Caseta Leap BridgeBridge is running on port 51856.
4/3/2022, 8:14:01 PMLutron Caseta Leap BridgeLutronCasetaLeapERRORCould not connect to discovered hub: Error: error:0909006C:PEM routines:get_name:no start line
    at node:internal/tls/secure-context:65:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:63:3)
    at configSecureContext (node:internal/tls/secure-context:152:5)
    at createSecureContext (node:_tls_common:117:3)
    at new LeapClient (/var/lib/hoobs/lutroncasetaleapbridge/node_modules/lutron-leap/src/LeapClient.ts:49:44)
    at LutronCasetaLeap.handleBridgeDiscovery (/var/lib/hoobs/lutroncasetaleapbridge/node_modules/homebridge-lutron-caseta-leap/src/platform.ts:183:28)
    at BridgeFinder.emit (node:events:520:28)
    at /var/lib/hoobs/lutroncasetaleapbridge/node_modules/lutron-leap/src/BridgeFinder.ts:47:26 {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}`

I'm adding to this issue since I'm having the same UI bug.

**Comment by cptgreedle** [comment] 2022-04-04 06:19
I’m having the same problem. When I install this in hoobs 2 things seem to happen. The bridge goes down and doesn’t go back up. And the plug-in won’t let me do anything. Like with the first poster, there are no buttons to push, no guides, the data I have access to is mostly blank. I really want to be able to use this plugin on hoobs, I just need to figure out how to make it work.

**Comment by thenewwazoo** [comment] 2022-04-04 14:16
I don’t use HOOBS, so I unfortunately don’t have any insight. Closing this as a dupe of #37

**Closed by thenewwazoo** 2022-04-04 14:16 UTC
Labels: question
