### ISSUE TITLE
Do not error when skipping natively supported device

### ISSUE THREAD

**Issue by rhwood** [thenewwazoo/homebridge-lutron-caseta-leap#86] opened 2022-11-06 20:29 UTC
**Is your feature request related to a problem? Please describe:**
Errors indicate problems that need to be fixed, but skipping devices natively supported by Homekit does not need to be fixed, yet it's logged as an error.

**Describe the solution you'd like:**
Skipping natively supported devices be logged as info messages or not logged at all.

**Describe alternatives you've considered:**
None.

**Additional context:**
None.

**Comment by thenewwazoo** [comment] 2022-11-06 22:22
I agree, just haven't had the time to fix it. Closing as a dupe of #71 :)

**Closed by thenewwazoo** 2022-11-06 22:22 UTC
Labels: enhancement
